### ISSUE TITLE
Make code re-compilable

### ISSUE THREAD

**Issue by GabrielRavier** [GabrielRavier/Cave-Story-Disassembly#3]
The outputted C code is not recompilable.

**Comment by GabrielRavier** [comment]
After closer inspection, it seems that it'd be a lot easier to just re-compile the C code than to try using the disassembled code since it seems that conversion won't actually be needed apart from re-coding a few lib functions (some are hand-made assembly so they prolly won't work properly if re-compiled)

**Comment by Leo40Git** [comment]
Why is this labeled "wontfix"? By the way, the README still calls the repo Cave-Story-Disassembly.

**Comment by GabrielRavier** [comment]
I had put the wontfix label some time ago because I didn't think IDA made reasonably recompilable code (I was wrong). Also, I changed the readme 1 minute before you posted this comment 😛 .

**Comment by GabrielRavier** [comment]
See https://github.com/GabrielRavier/CaveStoryRemake
